# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ergouzi/C/websocket_wanggou

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ergouzi/C/websocket_wanggou

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ergouzi/C/websocket_wanggou/CMakeFiles /home/ergouzi/C/websocket_wanggou//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ergouzi/C/websocket_wanggou/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named websocket_service

# Build rule for target.
websocket_service: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 websocket_service
.PHONY : websocket_service

# fast build rule for target.
websocket_service/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/websocket_service.dir/build.make CMakeFiles/websocket_service.dir/build
.PHONY : websocket_service/fast

src/cJSON.o: src/cJSON.c.o
.PHONY : src/cJSON.o

# target to build an object file
src/cJSON.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/websocket_service.dir/build.make CMakeFiles/websocket_service.dir/src/cJSON.c.o
.PHONY : src/cJSON.c.o

src/cJSON.i: src/cJSON.c.i
.PHONY : src/cJSON.i

# target to preprocess a source file
src/cJSON.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/websocket_service.dir/build.make CMakeFiles/websocket_service.dir/src/cJSON.c.i
.PHONY : src/cJSON.c.i

src/cJSON.s: src/cJSON.c.s
.PHONY : src/cJSON.s

# target to generate assembly for a file
src/cJSON.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/websocket_service.dir/build.make CMakeFiles/websocket_service.dir/src/cJSON.c.s
.PHONY : src/cJSON.c.s

src/playlist.o: src/playlist.c.o
.PHONY : src/playlist.o

# target to build an object file
src/playlist.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/websocket_service.dir/build.make CMakeFiles/websocket_service.dir/src/playlist.c.o
.PHONY : src/playlist.c.o

src/playlist.i: src/playlist.c.i
.PHONY : src/playlist.i

# target to preprocess a source file
src/playlist.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/websocket_service.dir/build.make CMakeFiles/websocket_service.dir/src/playlist.c.i
.PHONY : src/playlist.c.i

src/playlist.s: src/playlist.c.s
.PHONY : src/playlist.s

# target to generate assembly for a file
src/playlist.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/websocket_service.dir/build.make CMakeFiles/websocket_service.dir/src/playlist.c.s
.PHONY : src/playlist.c.s

src/rooms.o: src/rooms.c.o
.PHONY : src/rooms.o

# target to build an object file
src/rooms.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/websocket_service.dir/build.make CMakeFiles/websocket_service.dir/src/rooms.c.o
.PHONY : src/rooms.c.o

src/rooms.i: src/rooms.c.i
.PHONY : src/rooms.i

# target to preprocess a source file
src/rooms.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/websocket_service.dir/build.make CMakeFiles/websocket_service.dir/src/rooms.c.i
.PHONY : src/rooms.c.i

src/rooms.s: src/rooms.c.s
.PHONY : src/rooms.s

# target to generate assembly for a file
src/rooms.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/websocket_service.dir/build.make CMakeFiles/websocket_service.dir/src/rooms.c.s
.PHONY : src/rooms.c.s

src/websocket_service.o: src/websocket_service.c.o
.PHONY : src/websocket_service.o

# target to build an object file
src/websocket_service.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/websocket_service.dir/build.make CMakeFiles/websocket_service.dir/src/websocket_service.c.o
.PHONY : src/websocket_service.c.o

src/websocket_service.i: src/websocket_service.c.i
.PHONY : src/websocket_service.i

# target to preprocess a source file
src/websocket_service.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/websocket_service.dir/build.make CMakeFiles/websocket_service.dir/src/websocket_service.c.i
.PHONY : src/websocket_service.c.i

src/websocket_service.s: src/websocket_service.c.s
.PHONY : src/websocket_service.s

# target to generate assembly for a file
src/websocket_service.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/websocket_service.dir/build.make CMakeFiles/websocket_service.dir/src/websocket_service.c.s
.PHONY : src/websocket_service.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... websocket_service"
	@echo "... src/cJSON.o"
	@echo "... src/cJSON.i"
	@echo "... src/cJSON.s"
	@echo "... src/playlist.o"
	@echo "... src/playlist.i"
	@echo "... src/playlist.s"
	@echo "... src/rooms.o"
	@echo "... src/rooms.i"
	@echo "... src/rooms.s"
	@echo "... src/websocket_service.o"
	@echo "... src/websocket_service.i"
	@echo "... src/websocket_service.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

